In [1]:
import torch

## 1. 화면상에서 Pytorch에서 데이터를 저장하는 단위는?
a. Tensor

## 2. 1번 문제에 해당하는 것의 특징을 간력히 설명해 보세요.
a. 실제로 저장할때는 1열로 저장된다.

## 3. Pytorch에서 정수형 데이터를 저장하는 데이터 타입을 모두 나열하세요. 또 간단한 데이터 타입의 크기 설명도 함께 작성하세요
a. Longtensor : 64intTensor
   

## 4. Pytorch에 논리형 데이터로 저장 후 속성을 출력하는 코드를 작성하세요

In [8]:
# a.
data = [10,-5,1.4,7,0,-1,0]
torch.BoolTensor(data)

tensor([ True,  True,  True,  True, False,  True, False])

## 5. 10개의 0데이터를 2차원으로 저장코드를 작성하세요

In [58]:
a = torch.zeros(1,10,dtype=torch.int32)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=torch.int32)

## 6. 5개의 1 데이터가 대각선으로 저장되는 2차원 저장 코드를 작성하세요

In [25]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## 7. 5번에서 저장된 형태와 동일하지만 값이 3이 저장된 코드를 작성하세요

In [59]:
torch.full_like(a,3)

tensor([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]], dtype=torch.int32)

## 8. ndarray 데이터를 Pytorch에 저장하는 코드를 작성하세요

In [37]:
torch.randn(7)

tensor([-0.4612, -0.8898, -0.2159, -0.2395,  0.0779, -0.3766, -1.2692])

## 9. 아래 조건에 맞는 데이터를 Pytorch에 저장하는 코드를 작성하세요
- 데이터 임의의 값 : 1픽셀 0~ 255
- 이미지 크기 120X80은 tensor에서는 가로 세로가 바뀐다.

In [39]:
img = torch.
img

tensor(120)

## 11. 

In [52]:
data = torch.tensor([[90, 70, 80],[70, 100,80],[99,88,77]])
print(data.sum(dim=1))
print(data.max(dim=1))

tensor([240, 250, 264])
torch.return_types.max(
values=tensor([ 90, 100,  99]),
indices=tensor([0, 1, 0]))
