### softmax(), sigmoid() 함수 <hr>
- sigmoid() : y=wx+b 결과를 전달 ===> 반환 : 0.0 ~ 1.0 사이 값으로 변환 ==> 이진분류
- softmax() : y=wx+b 결과 여러개 전달 ===> 반환 : 여러개의 결과값의 합이 1.0이 되도록 변환 ==> 다중분류

In [2]:
## 모듈로딩
import torch                            # 파이토치 기본 모듈로 텐서 및 기본 함수들
import torch.nn.functional as F         # 파이토치 인공신경만 관련 함수들
import torch.nn as nn
import torch.optim as optim

In [3]:
# 임의 데이터 생성
data1 = torch.tensor([1,2,1,1,2])
data1.shape

torch.Size([5])

In [4]:
F.sigmoid(data1)

tensor([0.7311, 0.8808, 0.7311, 0.7311, 0.8808])

In [7]:
data2 = data1.unsqueeze(dim=0)      # 0을 주면 앞에, 1을 주면 뒤에 붙는다
data2.shape, data2

(torch.Size([1, 5]), tensor([[1, 2, 1, 1, 2]]))

In [8]:
input = torch.randn(2, 3)
input

tensor([[-1.6401,  0.6775, -1.0545],
        [-0.5932, -0.7467,  0.2982]])

In [9]:
output = F.softmax(input)
output

C:\Users\KDP-23\AppData\Local\Temp\ipykernel_19572\3683852505.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = F.softmax(input)


tensor([[0.0772, 0.7840, 0.1387],
        [0.2328, 0.1996, 0.5676]])

In [11]:
output.sum(dim=0)       # 열단위 합

tensor([0.3100, 0.9837, 0.7063])

In [13]:
output.sum(dim=1)       # 행단위 합

tensor([1.0000, 1.0000])

In [15]:
output.max(dim=1)       # 인덱스만 빼려면 인덱싱 하면 된다.

torch.return_types.max(
values=tensor([0.7840, 0.5676]),
indices=tensor([1, 2]))

In [16]:
output.max(dim=1)[1]

tensor([1, 2])