### 인공신경망 모델 클래스 만들기 <hr> 
- 부모 클래스 : nn.Module 상속 받음
- 필수 오버라이딩 메서드: __init__(), forward()
- 

[1] 모듈로딩 <hr>

In [2]:
import torch
import torch.nn as nn

In [20]:
# 로지스틱회귀 모델 클래스 생성
# -Linear+ sigmoid

class LogicLinear(nn.Module):
    # 모델 구조 설정
    def __init__(self,in_,out_):
        #부모 만들기
        super().__init__()
        self.layer1=nn.Linear(in_,10)
        self.sigmoid1=nn.Sigmoid()
        #변환을 해주는 녀석일 뿐, 다른 의미는 없다. layer자리에는 이름 맘대로 넣어도 된다.
        self.layer2=nn.Linear(10,out_)
        self.sigmoid2=nn.Sigmoid()  #만약 하나 더 넣는다면? 헌거의 열과 새거의 행이 같아야 한다.
        
    #순방향 학습 진행 콜백함수(순전파)
    def forward(self,x): #x가 입력 데이터,레이어에게 x를 주어야 한다.
        y=self.layer1(x)
        z=self.sigmoid1(y) #y는 시그모이드에게 가야한다.
        y=self.layer2(x)
        z=self.sigmoid2(y) #y는 시그모이드에게 가야한다.
        return z
        #y=self.layer1(x)
        #z=self.sigmoid(y)
        #return z
        
        

In [27]:

ll=LogicLinear(784,3)
print(f'모델 구조 확인==== :{ll}')

모델 구조 확인==== :LogicLinear(
  (layer1): Linear(in_features=784, out_features=10, bias=True)
  (sigmoid1): Sigmoid()
  (layer2): Linear(in_features=10, out_features=3, bias=True)
  (sigmoid2): Sigmoid()
)


In [28]:
ll.parameters()

<generator object Module.parameters at 0x000001FD1D284430>

In [29]:
print('f모델 구성 w,b ===== ')
for param in ll.parameters():
    print(param)

f모델 구성 w,b ===== 
Parameter containing:
tensor([[ 0.0332,  0.0273,  0.0135,  ...,  0.0029,  0.0046,  0.0196],
        [-0.0033,  0.0121,  0.0284,  ..., -0.0051, -0.0189, -0.0241],
        [ 0.0003,  0.0324,  0.0237,  ..., -0.0338,  0.0217, -0.0330],
        ...,
        [ 0.0274,  0.0348, -0.0198,  ..., -0.0261,  0.0203, -0.0248],
        [ 0.0162,  0.0239, -0.0223,  ...,  0.0337,  0.0059,  0.0050],
        [-0.0104, -0.0127, -0.0164,  ...,  0.0083, -0.0285, -0.0060]],
       requires_grad=True)
Parameter containing:
tensor([-0.0245, -0.0320, -0.0018,  0.0150, -0.0239, -0.0131,  0.0112, -0.0333,
        -0.0014,  0.0221], requires_grad=True)
Parameter containing:
tensor([[ 0.1687,  0.0879,  0.2873, -0.3088, -0.1024, -0.0176, -0.0377,  0.0200,
         -0.2974,  0.0411],
        [-0.0186,  0.2505,  0.2279,  0.1979,  0.1769,  0.1695,  0.0254,  0.1760,
         -0.1201, -0.0654],
        [ 0.1477, -0.2044,  0.2909, -0.2075,  0.1064, -0.1403,  0.1959, -0.2720,
          0.0016,  0.1619]], 