### Tensor shape 변경
  - reshape(), view() : 원소 갯수가 유지됨!, 기존 텐서 공유함

In [1]:
# 모듈 로딩
import torch

In [24]:
# 텐서 데이터 생성
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape, t1.ndim)

print(t1.shape, t1.dtype, t1.storage_offset(), t1.stride(), t1.is_contiguous())
print(t1, t1.data_ptr(), t1[0].data_ptr(), t1[1].data_ptr())

torch.Size([2, 3]) 2
torch.Size([2, 3]) torch.int64 0 (3, 1) True
tensor([[1, 2, 3],
        [4, 5, 6]]) 3207392663680 3207392663680 3207392663704


In [3]:
# [2,3] ===> [3,2] 형태 변경 : 원소 동일 6개
t1.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [4]:
# [2,3] ===> [6,1] 형태 변경 : 원소 동일 6개
t1.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [5]:
# [2,3] ===> [6,1] 형태 변경 
# 여기서 -1은 인덱싱의 의미가 아니라 원소 수를 알아서 행에 할당하라는 뜻
t1.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [6]:
# [2,3] ===> [6,1] 형태 변경 
# 여기서 -1은 인덱싱의 의미가 아니라 원소 수를 알아서 열을 할당하라는 뜻
t1.view(6,-1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [8]:
# tensor.reshape()
t1.reshape(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
# 원소 수 유지되어야함!
# RuntimeError: shape '[-1,7]' is invalid for input of size 6
# t1.reshape(-1,7)

### 전치 : 열과 행 변경

In [14]:
print(t1.shape)     # T를 통해 행렬이 변경

t2=t1.T
print(t2.shape, t2.is_contiguous())
# 뒤집으면 stride 정보 변경

torch.Size([2, 3])
torch.Size([3, 2]) False


In [13]:
# RuntimeError : view size is not compatible with input tensor's size and stride
# t2.view(-1,6)             #에러 발생

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [23]:
t2.reshape(-1,6)        # reshape은 가능!

tensor([[1, 2, 3, 4, 5, 6]])

Transform 했을 시 review는 바뀐 데이터정보를 그대로 불러오지만(142536) reshape은 다시 그 기준을 새로 지정한다(123456)

In [17]:
t3 = t2.reshape(-1,6)
print(t3, t3.is_contiguous())

tensor([[1, 4, 2, 5, 3, 6]]) True


### 텐서 데이터의 메모리 저장 정보 및 메타데이터
- 현재 저장형태, 검색 방향 정보, 시작 정보

In [19]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape, t1.ndim)
print(f't1.storage() => {t1.storage()}')
print(f't1.storage_offset() => {t1.storage_offset()}')
print(f't1.stride() => {t1.stride()}')      # 다음 줄을 가기 위해서는 몇칸 가야 하는가 (가로 기준)
print(f't1.is_contiguous() => {t1.is_contiguous()}')        # 연속적인가

torch.Size([2, 3]) 2
t1.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset() => 0
t1.stride() => (3, 1)
t1.is_contignous() => True


In [21]:
t2 = t1.view(-1,2)      # 행,열 변경 (원래 있던 주소는 변하지 않음)

print(f't2.storage() => {t2.storage()}')
print(f't2.storage_offset() => {t2.storage_offset()}')
print(f't2.stride() => {t2.stride()}')      # 다음 줄을 가기 위해서는 몇칸 가야 하는가 , 다음 칸 까지 얼마 가야하나
print(f't2.is_contiguous() => {t2.is_contiguous()}')        # 연속적인가

t2.storage() =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t2.storage_offset() => 0
t2.stride() => (2, 1)
t2.is_contiguous() => True


In [22]:
t2

tensor([[1, 2],
        [3, 4],
        [5, 6]])

### 차원 제거/추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze(dim) : 텐서에 차원 1인 것 추가

In [30]:
# 데이터 생성
t1 = torch.tensor([[1,2],[3,4]])
t2 = torch.tensor([[1,2,3,4]])
t3 = torch.tensor([[[1,2,3,4]]])

In [34]:
print(f't1 => {t1.shape}, {t1.ndim}D, {t1.data_ptr()}')
print(f't2 => {t2.shape}, {t2.ndim}D, {t2.data_ptr()}')
print(f't3 => {t3.shape}, {t3.ndim}D, {t3.data_ptr()}')

t1 => torch.Size([2, 2]), 2D, 3207392723136
t2 => torch.Size([1, 4]), 2D, 3207392723264
t3 => torch.Size([1, 1, 4]), 3D, 3207392723328


In [35]:
t11 = t1.squeeze()
t22 = t2.squeeze()
t33 = t3.squeeze()
t44 = t3.squeeze(dim=0)         # 지정된 것만 보게 한다(0번자리)
print(f't1 차원 축소 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}')
print(f't2 차원 축소 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}')
print(f't3 차원 축소 => {t33.shape}, {t33.ndim}D, {t33.data_ptr()}')
print(f't3 차원 축소 => {t44.shape}, {t44.ndim}D, {t44.data_ptr()}')
# shape안에서 1이라고 적힌 녀석을 줄인다(?)

t1 차원 축소 => torch.Size([2, 2]), 2D, 3207392723136
t2 차원 축소 => torch.Size([4]), 1D, 3207392723264
t3 차원 축소 => torch.Size([4]), 1D, 3207392723328
t3 차원 축소 => torch.Size([1, 4]), 2D, 3207392723328


In [36]:
## 원소/요소 수 변경 없이 1차원 증가 시키기 => torch.unsqueeze(dim)
t1.shape

torch.Size([2, 2])

In [37]:
print(f't1 정보 => {t1.shape}, {t1.ndim}D, {t1.data_ptr()}')

t1 정보 => torch.Size([2, 2]), 2D, 3207392723136


In [38]:
t11 = t1.unsqueeze(dim=0)
t22 = t1.unsqueeze(dim=-1)
print(f't1 차원 추가 => {t11.shape}, {t11.ndim}D, {t11.data_ptr()}, {t11.stride()}')
print(f't2 차원 추가 => {t22.shape}, {t22.ndim}D, {t22.data_ptr()}, {t22.stride()}')

t1 차원 추가 => torch.Size([1, 2, 2]), 3D, 3207392723136, (4, 2, 1)
t2 차원 추가 => torch.Size([2, 2, 1]), 3D, 3207392723136, (2, 1, 1)


### Tensor 차원/형태 변경

In [42]:
t1 = torch.tensor([[[1,2],[11,22],[44,55]]])
print(f't1 => {t1.shape}, {t1.ndim}D')

t1 => torch.Size([1, 3, 2]), 3D


In [45]:
# 2개의 차원을 변경하는 메서드 : transpose
t11 = t1.transpose(0, 2)
print(f't11 => {t11.shape}, {t11.ndim}D')

t11 => torch.Size([2, 3, 1]), 3D


In [46]:
# 모든 차원을 변경하는 메서드 : permute
t22 = t1.permute(1,2,0)
print(f't22 => {t22.shape}, {t22.ndim}D')

t22 => torch.Size([3, 2, 1]), 3D


In [47]:
print(f'{t1.data_ptr()}, {t11.data_ptr()}, {t22.data_ptr()}')

3207392664000, 3207392664000, 3207392664000


In [52]:
t1[None].shape      # 1차원 더 늘어난다

torch.Size([1, 1, 3, 2])

In [51]:
t1.shape

torch.Size([1, 3, 2])