### 텐서(Tensor) 살펴보기
- Pytorch에서 데이터 저장 자료형
- 모델 입력(input), 출력(output) 데이터 형태
- 

- 모듈로딩

In [1]:
import torch

- Tensor 속성 관련 함수

In [2]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명
def print_attribute(tensor, name):
    print(f'[Tensor{name}]\'s Attribute]')
    print(f' - tensor.shape : {tensor.shape}')
    print(f' - tensor.ndim : {tensor.ndim}')
    print(f' - tensor.dtype : {tensor.dtype}')
    print(f' - tensor.device : {tensor.device}')
    print(f' - tensor.requires_grad : {tensor.requires_grad}')
    print(f' - tensor.data \n{tensor.data}')

- Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    * 타입별 텐서 클래스 생성자 활용
    * 예) IntTensor(), FloatTensor(), BoolTensor()

In [15]:
# 정수 타입 텐서 생성
t1= torch.IntTensor(10) # t1은 1차원 스칼라값
t2 = torch.IntTensor([10.,20.]) # int 텐서에 실수를 넣어 경고 발생
t3 = torch.BoolTensor([1,1,0,-1]) # 0만 False 
t4= torch.FloatTensor([10,20])  # float라 실수로 바뀜

C:\Users\KDP-23\AppData\Local\Temp\ipykernel_20032\1016672282.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t2 = torch.IntTensor([10.,20.]) #


In [16]:
print_attribute(t1,'t1')
print_attribute(t2,'t2')
print_attribute(t3,'t3')
print_attribute(t4,'t4')

[Tensort1]'s Attribute]
 - tensor.shape : torch.Size([10])
 - tensor.ndim : 1
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
[Tensort2]'s Attribute]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
tensor([10, 20], dtype=torch.int32)
[Tensort3]'s Attribute]
 - tensor.shape : torch.Size([4])
 - tensor.ndim : 1
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
tensor([ True,  True, False,  True])
[Tensort4]'s Attribute]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
tensor([10., 20.])


- Tensor 생성 (2) 원하는 값으로 텐서 생성 => torch.tensor()

In [21]:
t1 = torch.tensor(10)       # scalar 데이터, int64
print_attribute(t1,'t1')

[Tensort1]'s Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0
 - tensor.dtype : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
10


In [20]:
t1 = torch.tensor(10.)    # scalar 데이터, float32
print_attribute(t1,'t1')

[Tensort1]'s Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
10.0


In [23]:
# dtype 매개변수 : 원하는 데이터 타입 지정 가능
t1 = torch.tensor(10., dtype=torch.bool)    # 강제로 int32로 타입 바꾸기  float32  --> bool      
print_attribute(t1,'t1')

[Tensort1]'s Attribute]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
True


In [24]:
t1= torch.tensor([1,2,3], dtype=torch.int8)     # 1D 데이터
print_attribute(t1,'t1')

[Tensort1]'s Attribute]
 - tensor.shape : torch.Size([3])
 - tensor.ndim : 1
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
tensor([1, 2, 3], dtype=torch.int8)


In [25]:
t1= torch.tensor([[1,2,3]], dtype=torch.int8)     # 2D 데이터
print_attribute(t1,'t1')

[Tensort1]'s Attribute]
 - tensor.shape : torch.Size([1, 3])
 - tensor.ndim : 2
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
tensor([[1, 2, 3]], dtype=torch.int8)


- Tensor 생성 (3) 특정 값으로 채운 텐서 => 0, 1 등의 값

In [26]:
# 0으로 채운 텐서
t1 = torch.zeros((5,5), dtype=torch.int8)
print_attribute(t1, 't1')

[Tensort1]'s Attribute]
 - tensor.shape : torch.Size([5])
 - tensor.ndim : 1
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
tensor([0., 0., 0., 0., 0.])


In [28]:
# 1으로 채운 텐서
t1 = torch.ones((2,4), dtype=torch.int8)
print_attribute(t1, 't1')

[Tensort1]'s Attribute]
 - tensor.shape : torch.Size([2, 4])
 - tensor.ndim : 2
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data 
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)


In [29]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like(), ones_like()
img= torch.tensor([[2,3,4,5,6,7],[2,3,4,5,6,7]])
print(img.shape)

torch.Size([2, 6])


In [30]:
zero_img = torch.zeros_like(img)
print(zero_img)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])


In [32]:
one_img = torch.ones_like(img)
print(one_img)

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])


In [33]:
full_img=torch.full_like(img,7)     # 7로 채우기
print(full_img)

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])


In [34]:
# 대각선 방향으로 1채우기 => eye()
t1 = torch.eye(5)
print(t1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [35]:
torch.manual_seed(12)           # 랜덤 초기값 설정

- Tensor 생성 방법(4): 임의의 값으로 채ㅇ

In [38]:
t5 = torch.rand(2,3)            # [0,1) 분포 안에서 랜덤 생성()
print(t5)

tensor([[0.1256, 0.4456, 0.6601],
        [0.0554, 0.1573, 0.8137]])


In [39]:
t6 = torch.randn(2,3)           # standard normal 분포에서 랜덤 생성
print(t6)

tensor([[ 0.1466, -1.0041, -0.7882],
        [-0.8074, -0.2957, -0.1462]])


In [41]:
t7 = torch.randint(low=1, high=10, size=(2,3))      # [low,high) low<=값 <high
print(t7)

tensor([[6, 7, 2],
        [1, 8, 8]])


- Tensor 생성 방법(5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), tensor()

In [42]:
# 데이터 생성
import numpy as np
data = np.array([11,22,33])
print(data, type(data))

[11 22 33] <class 'numpy.ndarray'>


In [43]:
t1 = torch.from_numpy(data)
print(t1)

tensor([11, 22, 33], dtype=torch.int32)


In [44]:
t2 = torch.as_tensor(data)
print(t2)

tensor([11, 22, 33], dtype=torch.int32)


In [45]:
t3 = torch.tensor(data)
print(t3)

tensor([11, 22, 33], dtype=torch.int32)


In [46]:
# ndarray 원소 변경
data[0] =100

In [47]:
# from_numpy, as_tensor() ==> 데이터 공유
# tensor() ==> 복사본 생성
print(data, t1, t2, t3, sep='\n')

[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)


- 브로드캐스팅 연산(덧셈)

In [48]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
m3 = m1+m2
print(m3, m3.shape)

tensor([4., 5.]) torch.Size([2])


In [50]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([[3],[4]])
m3 = m1+m2
print(f'm1.shape : {m1.shape}, m2.shape : {m2.shape}')
print(m3, m3.shape)

tensor([[4., 5.],
        [5., 6.]]) torch.Size([2, 2])


- 브로드캐스팅 연산(곱셈)

In [51]:
m3 = m1* m2
m4 = m1.mul(m2)
print(f'm3.shape => {m3.shape}\nm3 => \n{m3}')
print(f'm4.shape => {m4.shape}\nm3 => \n{m4}')

m3.shape => torch.Size([2, 2])
m3 => 
tensor([[3., 6.],
        [4., 8.]])
m4.shape => torch.Size([2, 2])
m3 => 
tensor([[3., 6.],
        [4., 8.]])


In [52]:
# 원소단위 연산 수행 메서드
m1.add(m2), m1.sub(m2), m1.mul(m2), m1.div(m2)

(tensor([[4., 5.],
         [5., 6.]]),
 tensor([[-2., -1.],
         [-3., -2.]]),
 tensor([[3., 6.],
         [4., 8.]]),
 tensor([[0.3333, 0.6667],
         [0.2500, 0.5000]]))