### 텐서 연결$ 결합

In [1]:
# 모듈로딩
import torch

In [10]:
# 텐서 데이터 생성
torch.manual_seed(12)

# 임의의 0.<=~<1. 실수
X = torch.rand(2, 10)
# 임의의 정수 : low<= ~ <high
y = torch.randint(0, 2, (10,))
y2 = torch.randint(0, 2, (2, 10))

In [17]:
print(y2)
print(X)

tensor([[1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 0, 0, 0, 0]])
tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456]])


In [11]:
print(f'X => {X.shape}, {X.ndim}D')
print(f'y => {y.shape}, {y.ndim}D')
print(f'y2 => {y2.shape}, {y2.ndim}D')

X => torch.Size([2, 10]), 2D
y => torch.Size([10]), 1D
y2 => torch.Size([2, 10]), 2D


In [12]:
# tensor 연결 cat([텐서1, 텐서2, ...]
xy1=torch.cat([X, y2], dim=1)
print(f'xy1 => {xy1.shape}, {xy1.ndim}D')

xy1 => torch.Size([2, 20]), 2D


In [13]:
xy1=torch.cat([X, y2], dim=0)
print(f'xy1 => {xy1.shape}, {xy1.ndim}D')

xy1 => torch.Size([4, 10]), 2D


In [18]:
print(xy1)

tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456],
        [1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])


In [20]:
# stack 은 행 방향으로 합치는 녀석들이다.
torch.stack([X,y2])

tensor([[[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421,
          0.7312, 0.7224],
         [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443,
          0.1256, 0.4456]],

        [[1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000,
          0.0000, 0.0000]]])

In [21]:
xy1.max()

tensor(1.)

In [23]:
xy1.max(dim=1)      # index까지 나옴

torch.return_types.max(
values=tensor([0.7312, 0.9790, 1.0000, 1.0000]),
indices=tensor([8, 6, 0, 2]))

In [27]:
# 행 단위로최댓값 및 최댓값의 인덱스
max_value = xy1.max(dim=1)[0]
max_index = xy1.max(dim=1)[1]

max_value, max_index

(tensor([0.7312, 0.9790, 1.0000, 1.0000]), tensor([8, 6, 0, 2]))

In [28]:
# 열 단위로최댓값 및 최댓값의 인덱스
max_value = xy1.max(dim=0)[0]
max_index = xy1.max(dim=0)[1]

max_value, max_index

(tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9790, 0.8443, 0.7312,
         0.7224]),
 tensor([2, 2, 3, 2, 2, 3, 1, 1, 0, 0]))

집계를 내는 집계함수이기 때문에 DF과는 다르게
column에서 집계를 내는 것이 최우선 단위이다.
dim=0일때 열 단위로 최댓값을 찾는 이유